#服务提供者
server:
  port: 9394    #服务器端口


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka 服务器地址
  instance:
    prefer-ip-address: true # IP 地址代替主机名注册
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ip-address}:${server.port} # 微服务节点实例名称
    appname: ec-zebra  #微服务名称
spring:
  application:
    name: ec-zebra