#网关服务提供者
server:
  port: 7790    #服务器端口

#spring.application.name：spring 应用名，未配置 eureka.instance.appname 时，spring 应用名默认为微服务名称
#其它需要代理的微服务未配置 spring.application.name 时，网关 zuul 会找不到本服务报错如：Load balancer does not have available server for client: xxx
spring:
  application:
    name: gateway-server

# 文件上传代理路径如果加了 zuul 前缀，网关中则可以不用设置文件上传大小,当然配置了也不影响
#  servlet:
#    multipart:
#      max-file-size: 2048MB
#      max-request-size: 2048MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka 服务器地址
  instance:
    prefer-ip-address: true # IP 地址代替主机名注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 微服务节点实例名称

zuul:
  #routes 配置路由规则，值是一个 Map，key 是代理的微服务名称，如 snow-leopard，值仍然还可以使用 map
  routes:
    snow-leopard:         #自定义名称，整个 routes 下唯一即可
      path: /leopardApp/**         #代理路径
      #      serviceId: snow-leopard   #代理的微服务名称，当它有多个节点时，网关默认会使用 ribbon 进行负载均衡
      strip-prefix: true        #是否剥离/去掉前缀，默认为 true，表示实际转发路径会去掉 path 中的前缀 leopard
    ec-zebra:
      path: /zebra/**
      serviceId: ec-zebra
      strip-prefix: false     # false 表示不剥离 path 中的前缀 zebra,此时前缀会被当作真实的请求路径
      sensitive-headers: Cookie,Set-Cookie  #过滤传入、传出的敏感头信息
#  ignored-patterns: /**/code/**,/**/cipher/**  #忽略请求路径中含有 code、cipher 字符串的请求，它们会被拦截，不会再转发

#配置 actuator
management:
  endpoint:
    health:
      show-details: always #将端点细节展示给所有用户查看，默认为 never(不展示细节给所有用户)
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream,routes,filters   #对外公开的端点，默认只公开了 health,info

#设置 hystrix 与 ribbon 超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

