#网关服务提供者
server:
  port: 7790    #服务器端口

#spring.application.name：spring 应用名，未配置 eureka.instance.appname 时，spring 应用名默认为微服务名称
#其它需要代理的微服务未配置 spring.application.name 时，网关 zuul 会找不到本服务报错如：Load balancer does not have available server for client: xxx
spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka 服务器地址
  instance:
    prefer-ip-address: true # IP 地址代替主机名注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 微服务节点实例名称

zuul:
  #  ignored-services: ec-zebra #对微服务 ec-zebra 不进行网关代理，值是一个 set，多个时用逗号隔开，* 表示所有
  #routes 配置路由规则，值是一个 Map，key 是代理的微服务名称，如 snow-leopard
  routes:
    snow-leopard: /leopard-server/** #后缀 "/**" 表示匹配所有请求
    #ec-zebra-toute 自定义名称，唯一即可，path 是映射路径，serviceId 是代理的服务名称
    ec-zebra-toute:
      path: /zebra-server/**
      serviceId: ec-zebra

