#服务消费者
server:
  port: 9395    #服务器端口

#spring.application.name：spring 应用名，未配置 eureka.instance.appname 时，spring 应用名默认为微服务名称
#spring.application.name未配置时，网关 zuul 会找不到本服务：Load balancer does not have available server for client: snow-leopard
spring:
  application:
    name: snow-leopard

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka 服务器地址

  instance:
    prefer-ip-address: true # IP 地址代替主机名注册
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ip-address}:${server.port} # 微服务节点实例名称
    appname: snow-leopard  #微服务名称，可以省略，推荐写 spring.application.name，或者两者都写上.

#配置 actuator
management:
  endpoint:
    health:
      show-details: always #将端点细节展示给所有用户查看，默认为 never(不展示细节给所有用户)

  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream   #对外公开 health,info,hystrix.stream 三个端点

feign:
  hystrix:
    enabled: true #开启 feign 的 hystrix 断路器功能，默认为 false，不开启
